### PR TITLE
make it easier to train your own model

### PR DESCRIPTION
**Pull request by LJXLJXLJX**
The organization of Synth_90k data set is very inefficient and hard to use.
I try to make it easier.

In order not to affect the normal use of the demo program, don't merge the char_dict.json and ord_map.json.

### CODE REVIEW

**Comment by MaybeShewill-CV** [comment]
@LJXLJXLJX The lexicon file is very useful in my opinion. I will force the encoding method when read the annotation file later. Thanks for push a request anyway:)

**Comment by LJXLJXLJX** [comment]
@MaybeShewill-CV 
Yes, I forgot to mention that, lexicon.txt should contain all the characters.
For chinese ocr, my lexicon.txt is like this
```
 
，
的
。
一
是
0
不
在
有
、
人
“
”
了
中
国
...
```

**Comment by MaybeShewill-CV** [comment]
@LJXLJXLJX Lexicon is a file record all the labels of dataset rather than the chinese charracter dict:)

**Comment by LJXLJXLJX** [comment]
@MaybeShewill-CV 
Thanks for mention that.
Now I want to train a Chinese OCR model.
I modify some codes, and put all the labels just in the annotation files like
 `20501375_18316197.jpg 2005年11月7日` because all my sentences are automatically generated, I can't build a lexcion.txt to store all those sentences ,which Synth_90k used to store all English words.
And I just regard the lexicon.txt as a character dict, now I am running the program to generate the tfrecords,I may take a long time.
Now I wonder will this method work on the later training step?

**Comment by MaybeShewill-CV** [comment]
@LJXLJXLJX The rest of the procedures are the same. I will upload a chinese ocr model later:)

**Pull request closed without merging**
